const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923135058517" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923135058517";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923195045539,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923195045539,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ",",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©MirZa" , // ```『 MirZa 』```", //*『• 』*\n youtube.com/@mirza"),
 
  author : process.env.PACK_AUTHER|| "MirZa-MD",
  packname: process.env.PACK_NAME || "MirZa",
  botname : process.env.BOT_NAME  || "MirZa",
  ownername:process.env.OWNER_NAME|| "MirZa",

  sessionName:process.env.SESSION_ID || "SUHAIL_19_26_10_28_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA0LFxuICAgICAgICA4NixcbiAgICAgICAgMTYwLFxuICAgICAgICAxMTYsXG4gICAgICAgIDUxLFxuICAgICAgICAxMjEsXG4gICAgICAgIDI0OSxcbiAgICAgICAgODQsXG4gICAgICAgIDk1LFxuICAgICAgICAyMzcsXG4gICAgICAgIDgsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMzEsXG4gICAgICAgIDEwNixcbiAgICAgICAgMjA0LFxuICAgICAgICAxMjYsXG4gICAgICAgIDE2MixcbiAgICAgICAgMCxcbiAgICAgICAgNSxcbiAgICAgICAgNzEsXG4gICAgICAgIDI0OSxcbiAgICAgICAgNjMsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTA1LFxuICAgICAgICA4MCxcbiAgICAgICAgMTc5LFxuICAgICAgICA1MSxcbiAgICAgICAgMTMzLFxuICAgICAgICAyMTAsXG4gICAgICAgIDU2LFxuICAgICAgICAyNDYsXG4gICAgICAgIDExOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2OSxcbiAgICAgICAgMTgyLFxuICAgICAgICAxOTksXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTAxLFxuICAgICAgICAxNDMsXG4gICAgICAgIDkzLFxuICAgICAgICA4MyxcbiAgICAgICAgNjYsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTE5LFxuICAgICAgICA4OCxcbiAgICAgICAgMjI1LFxuICAgICAgICA3OCxcbiAgICAgICAgNjAsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjMsXG4gICAgICAgIDIzMixcbiAgICAgICAgODcsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTIxLFxuICAgICAgICAxOTksXG4gICAgICAgIDk4LFxuICAgICAgICAzMyxcbiAgICAgICAgMjM1LFxuICAgICAgICA2NCxcbiAgICAgICAgMTM3LFxuICAgICAgICA3NCxcbiAgICAgICAgMTY3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTEyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3MixcbiAgICAgICAgMjgsXG4gICAgICAgIDMwLFxuICAgICAgICAyMTksXG4gICAgICAgIDM3LFxuICAgICAgICAxMDksXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjIyLFxuICAgICAgICAxOCxcbiAgICAgICAgNDIsXG4gICAgICAgIDEzLFxuICAgICAgICAxNjYsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTc1LFxuICAgICAgICAxMDQsXG4gICAgICAgIDU2LFxuICAgICAgICAxMTcsXG4gICAgICAgIDEwNSxcbiAgICAgICAgODYsXG4gICAgICAgIDI4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDE5MixcbiAgICAgICAgMjI0LFxuICAgICAgICAxMDQsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTAxLFxuICAgICAgICA0LFxuICAgICAgICAyMjAsXG4gICAgICAgIDE5MixcbiAgICAgICAgNTcsXG4gICAgICAgIDI0NCxcbiAgICAgICAgODBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzQsXG4gICAgICAgIDg5LFxuICAgICAgICAxMyxcbiAgICAgICAgNjUsXG4gICAgICAgIDUwLFxuICAgICAgICAxNzEsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjIsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTUwLFxuICAgICAgICA5OSxcbiAgICAgICAgOSxcbiAgICAgICAgNTMsXG4gICAgICAgIDEzOCxcbiAgICAgICAgNTAsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTc2LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTE1LFxuICAgICAgICAyMzgsXG4gICAgICAgIDExLFxuICAgICAgICA0MixcbiAgICAgICAgMTcwLFxuICAgICAgICA5MCxcbiAgICAgICAgOTYsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMjM5LFxuICAgICAgICAyMjgsXG4gICAgICAgIDkwLFxuICAgICAgICAxMTQsXG4gICAgICAgIDI2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzYsXG4gICAgICAgIDYyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDM5LFxuICAgICAgICA3NCxcbiAgICAgICAgNzYsXG4gICAgICAgIDYsXG4gICAgICAgIDg4LFxuICAgICAgICAzMSxcbiAgICAgICAgMjM5LFxuICAgICAgICA5NixcbiAgICAgICAgMTk5LFxuICAgICAgICA0MixcbiAgICAgICAgNDgsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTcsXG4gICAgICAgIDI1LFxuICAgICAgICAxODcsXG4gICAgICAgIDEyNyxcbiAgICAgICAgNzIsXG4gICAgICAgIDc1LFxuICAgICAgICAxMCxcbiAgICAgICAgNzMsXG4gICAgICAgIDczLFxuICAgICAgICAxOTIsXG4gICAgICAgIDQ2LFxuICAgICAgICAxMjksXG4gICAgICAgIDM5LFxuICAgICAgICAxNTcsXG4gICAgICAgIDgyXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQyLFxuICAgICAgICAyMzgsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTk2LFxuICAgICAgICAxODMsXG4gICAgICAgIDE3OCxcbiAgICAgICAgOTYsXG4gICAgICAgIDkwLFxuICAgICAgICA3OCxcbiAgICAgICAgMjA2LFxuICAgICAgICA1NixcbiAgICAgICAgMTA0LFxuICAgICAgICAzNSxcbiAgICAgICAgMjEzLFxuICAgICAgICAyNDYsXG4gICAgICAgIDg2LFxuICAgICAgICAxMzYsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMjMwLFxuICAgICAgICA0OSxcbiAgICAgICAgMzksXG4gICAgICAgIDg2LFxuICAgICAgICAxNzYsXG4gICAgICAgIDEyMyxcbiAgICAgICAgNjAsXG4gICAgICAgIDIxLFxuICAgICAgICAyNTEsXG4gICAgICAgIDg5LFxuICAgICAgICAxMDMsXG4gICAgICAgIDE2NyxcbiAgICAgICAgOTQsXG4gICAgICAgIDNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICAyNixcbiAgICAgICAgICA1MSxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICA0NSxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgNjRcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMixcbiAgICAgICAgICA2OCxcbiAgICAgICAgICA0MixcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgNDEsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMTlcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2NSxcbiAgICAgICAgMzYsXG4gICAgICAgIDE1NSxcbiAgICAgICAgNTksXG4gICAgICAgIDE0MixcbiAgICAgICAgODAsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTI2LFxuICAgICAgICAxMyxcbiAgICAgICAgMjA2LFxuICAgICAgICAxOTcsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTg1LFxuICAgICAgICAxNjYsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjYsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTkxLFxuICAgICAgICA4MixcbiAgICAgICAgNSxcbiAgICAgICAgMjIyLFxuICAgICAgICA4MyxcbiAgICAgICAgMjM3LFxuICAgICAgICA4MSxcbiAgICAgICAgNDYsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTIzLFxuICAgICAgICAxODksXG4gICAgICAgIDAsXG4gICAgICAgIDE1LFxuICAgICAgICA3OSxcbiAgICAgICAgMjUyLFxuICAgICAgICAyNDksXG4gICAgICAgIDEwMixcbiAgICAgICAgMTc1LFxuICAgICAgICA2NSxcbiAgICAgICAgMTI2LFxuICAgICAgICAyMjQsXG4gICAgICAgIDE5MSxcbiAgICAgICAgNSxcbiAgICAgICAgMTA0LFxuICAgICAgICA2MixcbiAgICAgICAgMTkzLFxuICAgICAgICAyNTIsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTk3LFxuICAgICAgICAxMjksXG4gICAgICAgIDExLFxuICAgICAgICAxODQsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTI4LFxuICAgICAgICAxMzUsXG4gICAgICAgIDcwLFxuICAgICAgICA2MSxcbiAgICAgICAgMTk0LFxuICAgICAgICAxOTAsXG4gICAgICAgIDExMCxcbiAgICAgICAgNzQsXG4gICAgICAgIDc0LFxuICAgICAgICAxMjksXG4gICAgICAgIDIyNCxcbiAgICAgICAgNixcbiAgICAgICAgMTgsXG4gICAgICAgIDE0M1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogNyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJ4cDRCbTM5dTQwYjhodHlzemNxNHRFdU82OFdva3hCRXJJVENyM0MvN1VBPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJ1Sk9qQnJTMVJ0Ry1XanB3VWMteGVRXCIsXG4gIFwicGhvbmVJZFwiOiBcImIwNzE3NjZkLTgwZDktNDNmYi04MGE4LTg5NWZkMGQ1N2IzZFwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA3NixcbiAgICAgIDIwMixcbiAgICAgIDAsXG4gICAgICAxOTMsXG4gICAgICA4OCxcbiAgICAgIDMxLFxuICAgICAgMTEwLFxuICAgICAgNzMsXG4gICAgICAyMDYsXG4gICAgICAyNTIsXG4gICAgICAxOTUsXG4gICAgICAxNTksXG4gICAgICAyMDMsXG4gICAgICAxMzAsXG4gICAgICAyNixcbiAgICAgIDIwNyxcbiAgICAgIDcxLFxuICAgICAgMTgzLFxuICAgICAgOCxcbiAgICAgIDE5N1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTA0LFxuICAgICAgNTUsXG4gICAgICAyNDcsXG4gICAgICAyNDMsXG4gICAgICAxNDcsXG4gICAgICAxMDEsXG4gICAgICAxMjAsXG4gICAgICAxODIsXG4gICAgICAxMzUsXG4gICAgICAxMDIsXG4gICAgICAyMTUsXG4gICAgICAzMixcbiAgICAgIDI0MSxcbiAgICAgIDE5LFxuICAgICAgMTk4LFxuICAgICAgNzYsXG4gICAgICAxOTIsXG4gICAgICAyMjIsXG4gICAgICAxMjMsXG4gICAgICAxMjFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNOTEozMGNRNWNyL3VBWVlCeUFBS0FBPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcImM0eHVBUXR3R0JITEtlVlNhQUI2aHB4OW9MRFB4eHhXaCszWnhPMHE2VFE9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiUFJFVzh0aHBFOGc5TklybzdONXhnY25HQS9xSVBPOVVIRWNod3JZMURPczZnWEh6bHRXWnBUc2ZiVGVaTXpOWDJwdFZxR2YrVGlZTDF4T2M3Rm41Q1E9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiYkcybU1UNGh2UGZMdm90cmpUdE8rVzVQMm1wUmFOeEo5S05jb2VIdnhabTVzcXY4SUZjTXBqcDZXSTJKVnpHNFVXb2ZoMUVUMUFhSDdkVU5VaERmakE9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMxMzUwNTg1MTc6MTVAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJNaXJaYVwiLFxuICAgIFwibGlkXCI6IFwiMjgwNjU5NTAzMzgyNzI2OjE1QGxpZFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzMTM1MDU4NTE3OjE1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDQxLFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDUyXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MzAxNDM1OTMsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFQaFdcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQVBoVy5qc29uIjogIntcImtleURhdGFcIjpcIjQxT1l6d2Z1RlZycGFuQU9saHpFZ0VCN3BrdElBM1ZnamdqTmRxWUh4MGc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTUwNDYzNjk4LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQaFguanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI0Y3A0NVdGMmJJUElnZUZubmRRUVFNeDRUQXR3UXBmWEgyWmhTcGVJMndBPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1MDQ2MzY5OCxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMl19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUGhZLmpzb24iOiAie1wia2V5RGF0YVwiOlwiOHZKcW8rLzVCK3BtbG5DNE9hWEJmSndKT3QybFI3OUlYTUVYS0lXQ0VnUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNTA0NjM2OTgsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDJdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQVBoWi5qc29uIjogIntcImtleURhdGFcIjpcIjlxT2ovUHhpeGRScFhnZi9lekxRRTQyQXF4Z3B1NUhlNHNYMnF0SjBZUHc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTUwNDYzNjk4LFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMCwyLDRdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQVBoYS5qc29uIjogIntcImtleURhdGFcIjpcIlVUN0s4VVBxaUlkWXNJMkt5d3J0S25VM0tvaDhqUU9rZm5hWWxHa0pkdEE9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTUwNDYzNjk4LFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMCwyXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MzAxMTkxMjE3MjRcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQaGIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI4RkdJbVc5K1ZiTlRRUkYzNGdscDA1S1MyV1o2MmRPNEVHbmc2d2VKUUxnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1MDQ2MzY5OCxcImN1cnJlbnRJbmRleFwiOjYsXCJkZXZpY2VJbmRleGVzXCI6WzAsMl19LFwidGltZXN0YW1wXCI6XCIxNzMwMTQzNTY2NjYwXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
